#!/bin/bash
#SBATCH --partition=EPYC
#SBATCH --job-name=sequenza
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=20G
#SBATCH --time=96:00:00
#SBATCH --output=seq_%J.out 
#SBATCH --error=seq_%J.err
#SBATCH -A lade

module load java
module load singularity

base=/orfeo/scratch/area/lvaleriani/races/ProCESS-examples/sequenza
config=$base/myconfig
/orfeo/cephfs/scratch/cdslab/shared/SCOUT/nextflow run $base/main.nf -profile singularity,genoa -c $config -resume
